// Generates a dialect-neutral Z80 source that exercises every branch of
// src/asm/encode.ts. The output is committed as opcodes.neutral.asm and checked
// against our assembler, rasm and pasmo.
//
// Rules: `0x` hex only, decimal displacements, `db`/`equ`/`org`, explicit
// labels, no `$`, lower case — the subset all three assemblers accept.

const R8 = ['b', 'c', 'd', 'e', 'h', 'l', '(hl)', 'a'];
const RP = ['bc', 'de', 'hl', 'sp'];
const RP2 = ['bc', 'de', 'hl', 'af'];
const CC = ['nz', 'z', 'nc', 'c', 'po', 'pe', 'p', 'm'];
const ALU = ['add a,', 'adc a,', 'sub ', 'sbc a,', 'and ', 'xor ', 'or ', 'cp '];
const SHIFTS = ['rlc', 'rrc', 'rl', 'rr', 'sla', 'sra', 'sll', 'srl'];
const IDX = ['ix', 'iy'];

export function opcodeCorpus(): string {
  const L: string[] = [];
  const e = (s: string) => L.push(s);

  e('; generated by gen-opcodes.ts — regenerate, do not hand-edit');
  e('nn   equ 0x1234');
  e('     org 0x8000');

  // --- no-operand -------------------------------------------------
  for (const m of [
    'nop', 'halt', 'di', 'ei', 'exx', 'rlca', 'rrca', 'rla', 'rra', 'daa', 'cpl',
    'scf', 'ccf', 'neg', 'retn', 'reti', 'rrd', 'rld',
    'ldi', 'ldd', 'ldir', 'lddr', 'cpi', 'cpir', 'cpd', 'cpdr',
    'ini', 'inir', 'ind', 'indr', 'outi', 'otir', 'outd', 'otdr',
  ]) e('     ' + m);

  // --- 8-bit loads ---------------------------------------------
  for (const d of R8) for (const s of R8) {
    if (d === '(hl)' && s === '(hl)') continue; // that encoding is halt
    e(`     ld ${d},${s}`);
  }
  for (const d of R8) e(`     ld ${d},0x2a`);
  for (const rr of ['bc', 'de']) { e(`     ld a,(${rr})`); e(`     ld (${rr}),a`); }
  e('     ld a,(nn)');
  e('     ld (nn),a');
  e('     ld a,i'); e('     ld a,r'); e('     ld i,a'); e('     ld r,a');

  // --- 16-bit loads ------------------------------------------
  for (const rr of RP) e(`     ld ${rr},0x89ab`);
  e('     ld hl,(nn)'); e('     ld (nn),hl');
  for (const rr of ['bc', 'de', 'sp']) { e(`     ld ${rr},(nn)`); e(`     ld (nn),${rr}`); }
  e('     ld sp,hl');
  for (const ix of IDX) {
    e(`     ld ${ix},0x89ab`);
    e(`     ld ${ix},(nn)`);
    e(`     ld (nn),${ix}`);
    e(`     ld sp,${ix}`);
    e(`     ld ${ix}h,0x12`); e(`     ld ${ix}l,0x34`);
    e(`     ld ${ix}h,b`); e(`     ld c,${ix}l`);
  }

  // --- push / pop --------------------------------------------
  for (const rr of RP2) { e(`     push ${rr}`); e(`     pop ${rr}`); }
  for (const ix of IDX) { e(`     push ${ix}`); e(`     pop ${ix}`); }

  // --- exchange ---------------------------------------------
  e("     ex af,af'");
  e('     ex de,hl');
  e('     ex (sp),hl');
  for (const ix of IDX) e(`     ex (sp),${ix}`);

  // --- 8-bit arithmetic / logic --------------------------------
  for (const op of ALU) {
    for (const s of R8) e(`     ${op}${s}`);
    e(`     ${op}0x2a`);
    for (const ix of IDX) {
      e(`     ${op}(${ix}+5)`);
      e(`     ${op}(${ix}-3)`);
      e(`     ${op}${ix}h`);
      e(`     ${op}${ix}l`);
    }
  }

  // --- inc / dec ---------------------------------------------
  for (const m of ['inc', 'dec']) {
    for (const r of R8) e(`     ${m} ${r}`);
    for (const rr of RP) e(`     ${m} ${rr}`);
    for (const ix of IDX) {
      e(`     ${m} ${ix}`);
      e(`     ${m} (${ix}+1)`);
      e(`     ${m} ${ix}h`);
      e(`     ${m} ${ix}l`);
    }
  }

  // --- 16-bit arithmetic ------------------------------------
  for (const rr of RP) { e(`     add hl,${rr}`); e(`     adc hl,${rr}`); e(`     sbc hl,${rr}`); }
  for (const ix of IDX) for (const rr of ['bc', 'de', 'sp', ix]) e(`     add ${ix},${rr}`);

  // --- rotates / shifts / bit ops -----------------------------
  for (const sh of SHIFTS) {
    for (const r of R8) e(`     ${sh} ${r}`);
    for (const ix of IDX) e(`     ${sh} (${ix}+2)`);
  }
  for (const m of ['bit', 'res', 'set']) {
    for (let b = 0; b < 8; b++) {
      for (const r of R8) e(`     ${m} ${b},${r}`);
      for (const ix of IDX) e(`     ${m} ${b},(${ix}+4)`);
    }
  }

  // --- jump / call / ret --------------------------------------
  e('     jp nn');
  for (const c of CC) e(`     jp ${c},nn`);
  e('     jp (hl)');
  for (const ix of IDX) e(`     jp (${ix})`);
  e('     call nn');
  for (const c of CC) e(`     call ${c},nn`);
  e('     ret');
  for (const c of CC) e(`     ret ${c}`);
  for (let t = 0; t <= 0x38; t += 8) e(`     rst 0x${t.toString(16)}`);

  // --- relative jumps (real targets) ------------------------
  e('     jr fwd');
  e('     jr nz,fwd');
  e('     jr z,fwd');
  e('     jr nc,fwd');
  e('     jr c,fwd');
  e('     djnz fwd');
  e('     defs 20');
  e('fwd: nop');
  e('     jr fwd'); // backward

  // --- I/O -------------------------------------------------
  e('     in a,(0x40)');
  e('     out (0x40),a');
  for (const r of R8) if (r !== '(hl)') e(`     in ${r},(c)`);
  e('     in f,(c)');
  for (const r of R8) if (r !== '(hl)') e(`     out (c),${r}`);
  e('     out (c),0');

  // --- interrupt modes ------------------------------------
  e('     im 0'); e('     im 1'); e('     im 2');

  // --- misc directives ------------------------------------
  e('     db 0x01, 0x02, 0xff, 65, "AB"');
  e('     dw 0x1234, nn');
  e('     defs 4, 0xaa');

  e('done: nop');
  return L.join('\n') + '\n';
}
